import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppWalletProvider from "./context/AppWalletProvider";
import { WalletChangeProvider } from "./context/WalletChangeProvider";
import { SelectTokenProvider } from "./context/SelectTokenProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {
          <AppWalletProvider>
            <WalletChangeProvider>
              <SelectTokenProvider>{children}</SelectTokenProvider>
            </WalletChangeProvider>
          </AppWalletProvider>
        }
      </body>
    </html>
  );
}
